name: Update Message of the Day

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-motd:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Select random MOTD
        run: |
          # Read all messages from motd.txt
          readarray -t message_array < motd.txt
          
          # Count non-empty lines
          TOTAL_MESSAGES=${#message_array[@]}
          
          # Select random index
          RANDOM_INDEX=$(( $RANDOM % $TOTAL_MESSAGES ))
          
          # Get selected message
          SELECTED_MESSAGE="${message_array[$RANDOM_INDEX]}"
          
          # Build JSON content
          JSON_CONTENT="{\n"
          JSON_CONTENT+="  \"selectedMessage\": $SELECTED_MESSAGE,\n"
          JSON_CONTENT+="  \"messages\": [\n"
          
          # Add all messages with proper commas
          for (( i=0; i<$TOTAL_MESSAGES; i++ )); do
            JSON_CONTENT+="    ${message_array[$i]}"
            if (( i < $TOTAL_MESSAGES-1 )); then
              JSON_CONTENT+=",\n"
            else
              JSON_CONTENT+="\n"
            fi
          done
          
          JSON_CONTENT+="  ]\n"
          JSON_CONTENT+="}\n"
          
          # Write to file
          echo -e "$JSON_CONTENT" > motd.json
