name: Update Message of the Day

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-motd:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Select random MOTD
        run: |
          # Install jq for JSON processing
          sudo apt-get update && sudo apt-get install -y jq
          
          # Read messages and remove quotes and commas
          readarray -t raw_message_array < motd.txt
          message_array=()
          
          for msg in "${raw_message_array[@]}"; do
            # Remove quotes and trailing comma
            cleaned_msg=$(echo "$msg" | sed 's/^"//' | sed 's/",$\|"$//')
            
            if [ ! -z "$cleaned_msg" ]; then
              message_array+=("$cleaned_msg")
            fi
          done
          
          # Get random index
          random_index=$(( RANDOM % ${#message_array[@]} ))
          
          # Select random message
          selected_message="${message_array[$random_index]}"
          
          # Build JSON with jq (without adding extra quotes)
          echo '{' > motd.json
          echo "  \"selectedMessage\": \"$selected_message\"," >> motd.json
          echo '  "messages": [' >> motd.json
          
          # Add each message to the JSON
          for (( i=0; i<${#message_array[@]}; i++ )); do
            echo -n "    \"${message_array[$i]}\"" >> motd.json
            if [ $i -lt $((${#message_array[@]}-1)) ]; then
              echo "," >> motd.json
            else
              echo "" >> motd.json
            fi
          done
          
          echo '  ]' >> motd.json
          echo '}' >> motd.json
          
          # Show result for logging
          cat motd.json
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'github-action@users.noreply.github.com'
          git add motd.json
          git commit -m "Update MOTD for $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push
